import streamlit as st
from forms.contact import contact_form

st.title("About Us", anchor=False)

@st.dialog("Contact Me")
def show_contact_form():
    contact_form()


col1, col2 =st.columns(2) 

with col1:
    st.subheader("Nextgen Academy", anchor=False)
    st.caption("🚀 A young growing Tech Firm")



    
    
with col2:
    if st.button("Get In Touch", icon=":material/pinch:", key="contact-button"):
        show_contact_form()
    
    
    st.html(
        """
        <style>
        .st-key-contact-button{
        background-color: #1C0113;
        height: fit-content;
        width: 100%;
        padding: 25px;
        border:none;
        border-radius: 12px;
        
        }
        </style>
    
        """
    )

with st.sidebar:
    st.markdown("## 🏠 House Predictor")
    st.caption("California House Prediction Model")
    st.divider()

    st.markdown("### ⚙️ Model Settings")
    st.caption("Adjust Your Model Here")
    st.divider()

    st.caption("© 2026 California House Prediction Model")



st.subheader("Who We Are", anchor=False)
st.write("""
Welcome to the California House Prediction Model. We are a team of developers and 
students interested in Artificial Intelligence, Machine Learning, and Data Science.
""")
st.write("""This application was developed to demonstrate how machine learning can 
"be used to analyze housing data and estimate the value of a house based on different
"characteristics.""")

st.subheader("About the Project", anchor=False)

st.write("""
The California House Prediction Model uses a Machine Learning model trained on housing 
data from California. Users can provide information such as median income, house age, 
average number of rooms, population, location, and other housing characteristics.
""")
st.write("The model then analyzes these inputs and provides an estimated house value.")

st.write("""
Our goal is to demonstrate how data-driven technologies can be applied to real-world 
problems and how machine learning can support better understanding and decision-making 
in the housing sector.
""")

st.subheader("Our Mission", anchor=False)
st.write("""
Our mission is to make machine learning applications simple, understandable, and accessible 
while providing users with practical examples of how data can be transformed into useful 
predictions.
""")

st.subheader("Meet the Developers", anchor=False)
st.write("This application was developed as part of an academic and practical machine learning project.")

st.write("Developer: Fawzan Mohammed")
st.write("Student from KNUST School Of Business")
st.write("Program Of Study: Busness Information Technology (BIT)")

st.subheader("Disclaimer", anchor=False)
st.warning("""
The predictions generated by this application are estimates for educational and demonstration 
purposes only. They should not be considered professional property valuations or used as the 
sole basis for financial or real-estate decisions.
""")

