import streamlit as st


with st.sidebar:
    st.markdown("## 🏠 House Predictor")
    st.caption("California House Prediction Model")
    st.divider()

    st.markdown("### ⚙️ Model Settings")
    st.caption("Adjust Your Model Here")
    st.divider()
    
    st.caption("© 2026 California House Prediction Model")


st.title("Terms of Use", anchor=False)
st.subheader("1. Acceptance of Terms", anchor=False)
st.write("""
By accessing and using the California House Prediction Model, you agree to comply 
with and be bound by these Terms of Use. If you do not agree with any part of these 
terms, please discontinue use of the application.
""")

st.subheader("2. Purpose of the Application", anchor=False)
st.write("""
The California House Prediction Model is developed primarily for educational, research, 
and demonstration purposes. The application demonstrates how machine learning can be applied 
to housing data to generate estimated property values.
""")

st.subheader("3. Predictions and Accuracy", anchor=False)
st.write("""
The predictions provided by this application are generated by a machine learning model based 
on the data and variables used during its training.  Although efforts have been made to develop
and test the model, we do not guarantee that the predictions are completely accurate, reliable, 
or suitable for real-world property valuation.
""")
st.warning("Actual property values may differ due to factors that are not considered by the model.")

st.subheader("4. No Professional Advice", anchor=False)
st.write("""
The information and predictions provided by this application should not be considered professional 
real-estate, financial, investment, or valuation advice. Users should consult qualified professionals 
before making important financial or property-related decisions.
""")

st.subheader("5. User Responsibility", anchor=False)
st.write("""
Users are responsible for the information they provide to the application and for how they interpret and 
use the predictions generated. The developers shall not be held responsible for decisions, losses, damages, 
or other consequences resulting from reliance on the predictions provided by the application.
""")

st.subheader("6. Data and Privacy", anchor=False)
st.write("""
The application may process the information entered by users to generate predictions. Users should avoid 
entering sensitive, confidential, or personally identifiable information unless explicitly required by the 
application.
""")

st.subheader("7. Intellectual Property", anchor=False)
st.write("""
The application, including its design, source code, content, and other components, is protected by applicable 
intellectual property laws unless otherwise stated.
""")

st.write("""
Users may not reproduce, modify, distribute, or commercially exploit the application or its components without 
appropriate permission from the developers.
""")

st.subheader("8. Availability of the Application", anchor=False)
st.write("""
We make reasonable efforts to keep the application available and functioning properly. However, we do not guarantee 
that the application will always be available, uninterrupted, or free from errors.
""")
st.write("""The application may be modified, updated, temporarily suspended, or discontinued at any time.
""")

st.subheader("9. Limitation of Liability", anchor=False)
st.write("""To the extent permitted by applicable law, the developers shall not be liable for any direct or indirect
loss, damage, or expense arising from the use of, or inability to use, this application or reliance on its predictions.
""")

st.subheader("10. Changes to These Terms", anchor=False)
st.write("""We reserve the right to update or modify these Terms of Use when necessary. Any changes will take effect when 
the updated terms are made available on this page. Users are encouraged to review this page periodically for any changes.
""")

st.subheader("11. Contact", anchor=False)
st.write("""If you have questions, comments, or concerns regarding these Terms of Use or the application, please contact 
the development team through the contact information provided on the application.
""")

st.subheader("Final Disclaimer", anchor=False)
st.warning("""The California House Prediction Model is an educational machine learning application. All predictions are 
estimates and should not be treated as professional property valuations or as the sole basis for financial, investment, 
or real-estate decisions.
""")



